<html>

<!-- Mirrored from 62.4.17.167/sdz/sdz/les-exceptions-9.html by HTTrack Website Copier/3.x [XR&CO'2013], Sun, 27 Oct 2013 05:39:43 GMT -->

<!-- Mirrored from sdz.tdct.org/sdz/les-exceptions-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Nov 2015 05:00:15 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Tutoriel : Les exceptions</title>
<link href="medias/sdz_main.css" type="text/css" rel="stylesheet" media="all"/>
</head>
        <body>
<a href="../www.siteduzero.com/informatique/tutoriels/les-exceptions-9.html" class="version_en_ligne">Version en ligne</a>
<h1>Tutoriel : Les exceptions</h1>
<h2>Table des matières</h2><div class="table_des_matieres"><a href="#Lesexceptions">Les exceptions</a><br/><a href="#Lesmots-clstryexceptelseetfinally">Les mots-clés try, except, else et finally</a><br/><a href="#Listedesexceptionsbuilt-in">Liste des exceptions built-in</a><br/><a href="#Vospropresexceptions">Vos propres exceptions</a><br/></div>
<a name="Lesexceptions"></a><h2>Les exceptions</h2><div class="paginate-tuto">
<a class="after" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/les-mots-cles-try-except-else-et-finally">
<span class="next">Les mots-clés try, except, else et finally</span>
<span class="arrow"></span>
</a>
</div>
<hr class="top"/>
<div class="clear"></div> <div class="content">
<p id="r-569983" data-claire-element-id="569983">Si vous codez en Python, vous avez sûrement déjà été confronté(e) à des erreurs diverses, provenant de l'utilisateur, d'une bibliothèque, etc.<br/> Par exemple, vous souhaitez que l'utilisateur entre un nombre et que votre programme affiche le triple de ce nombre.<br/> Si vous utilisez <code data-claire-semantic="python">input() </code>, mais que l'utilisateur entre une chaîne de caractères (sans l'entourer de guillemets), le programme plante lamentablement.<br/> Si vous utilisez <code data-claire-semantic="python">raw_input() </code>, vous n'avez pas de problème lors de la saisie, mais vous vous retrouvez avec une chaîne. Or, vous avez besoin d'un nombre.<br/> Si vous utilisez <code data-claire-semantic="python">int() </code> pour transformer la chaîne obtenue en nombre, le programme plantera aussi dans le cas où l'utilisateur n'a pas entré un nombre.<br/> Alors, comment remédier à un tel problème ?</p><p id="r-569984" data-claire-element-id="569984">Ce tutoriel va vous expliquer comment gérer les erreurs en Python.<br/> Une première partie vous enseignera comment utiliser les mots-clé <code data-claire-semantic="python">try </code>, <code data-claire-semantic="python">except </code>, <code data-claire-semantic="python">finally </code> et <code data-claire-semantic="python">else </code>, tandis que la seconde vous présentera une liste des exceptions et des exemples les expliquant. Enfin, la troisième vous expliquera comment créer vos propres exceptions.</p>
</div><a name="Lesmots-clstryexceptelseetfinally"></a><h2>Les mots-clés try, except, else et finally</h2><div class="paginate-tuto">
<a class="after" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
<span class="next">Liste des exceptions built-in</span>
<span class="arrow"></span>
</a>
</div>
<hr class="top"/>
<div class="clear"></div> <div id="content" role="article">
<p id="r-569985" data-claire-element-id="569985">Quatre mots-clés vont servir à gérer les erreurs.</p><p id="r-569986" data-claire-element-id="569986"><code data-claire-semantic="python">try </code> permet « d'essayer » un bout de code. Si une erreur est rencontrée, on cesse d'interpréter le code et on passe aux <code data-claire-semantic="python">except </code>, qui permettent d'agir en fonction de l'erreur qui s'est produite. C'est pourquoi <code data-claire-semantic="python">try </code> doit <strong>toujours</strong> être suivi d'au moins un <code data-claire-semantic="python">except </code> ou d'un <code data-claire-semantic="python">finally </code>.<br/> Nous allons, pour comprendre leur fonctionnement, analyser le code suivant.</p><pre id="r-569987" data-claire-element-id="569987"><code data-claire-semantic="python">try:
    fichier = open(&quot;foo.txt&quot;, &quot;r&quot;)
    print int(&quot;abc&quot;)
except IOError:
    print &quot;Erreur lors de l'ouverture du fichier !&quot;
except ValueError:
    print &quot;Erreur lors de la conversion !&quot;</code></pre><p id="r-569988" data-claire-element-id="569988">Les deux premières lignes, dans le <code data-claire-semantic="python">try: </code>, sont tout d'abord interprétées. La première tente d'ouvrir un fichier appelé <em>foo.txt</em>. <em>Si ce fichier existe dans le répertoire du script, remplacez &quot;foo.txt&quot; par autre chose, de sorte que le fichier que le script tente d'ouvrir n'existe pas.</em><br/> La seconde essaie d'afficher à l'écran la chaîne &quot;abc&quot; convertie en nombre. <br/> La troisième ligne, qui contient le mot-clé <code data-claire-semantic="python">except </code>, est exécutée en cas d'<code data-claire-semantic="python">IOError </code>. <code data-claire-semantic="python">IOError </code> est l'exception lancée lorsqu'il s'avère impossible d'ouvrir un fichier (entre autres). Dans ce cas, on affiche une erreur. La cinquième ligne agit comme la troisième, en cas de <code data-claire-semantic="python">ValueError </code>, qui est lancé quand on passe un argument avec le bon type (ici, &quot;abc&quot; est bien une chaîne), mais que la valeur n'est pas correcte (&quot;abc&quot; ne saurait être transformée en nombre, vous en conviendrez).<br/> Lorsque nous lançons ce code, comme <em>foo.txt</em> n'existe pas, l'ouverture du fichier provoque une <code data-claire-semantic="python">IOError </code>. Si nous le créons (<code data-claire-semantic="bash">touch foo.txt </code> sous UNIX), alors la ligne <code data-claire-semantic="python">print int(&quot;abc&quot;) </code> sera interprétée et lancera une <code data-claire-semantic="python">ValueError </code>. Si, enfin, nous remplaçons <code data-claire-semantic="python">&quot;abc&quot; </code> par <code data-claire-semantic="python">&quot;22&quot; </code> (ou toute autre chaîne qui peut être convertie en nombre), alors aucune exception ne sera lancée et seul le bloc <code data-claire-semantic="python">try: </code> aura été exécuté.</p><p id="r-569989" data-claire-element-id="569989">On peut également mettre un <em>tuple</em> d'exceptions, pour les cas où le même code doit être interprété pour des erreurs différentes :</p><pre id="r-569990" data-claire-element-id="569990"><code data-claire-semantic="python">except (IOError, ValueError):</code></pre><p id="r-569991" data-claire-element-id="569991">Il est possible de créer une instance de l'exception, afin d'avoir plus d'informations sur une erreur :</p><pre id="r-569992" data-claire-element-id="569992"><code data-claire-semantic="python">try:
    fichier = open('foo.txt')
except IOError, e:
    print e</code></pre><pre id="r-569993" data-claire-element-id="569993"><code data-claire-semantic="console">[Errno 2] No such file or directory: 'foo.txt'</code></pre><aside id="r-569995" data-claire-element-id="569995" data-claire-semantic="warning"><p id="r-569994" data-claire-element-id="569994">Il ne faut <strong>pas</strong> utiliser <code data-claire-semantic="python">except: </code> tout seul, car des exceptions comme celles lancées lorsque l'utilisateur tente de quitter risquent d'être interceptées, et donc d'empêcher celui-ci d'y parvenir. Si vous voulez intercepter toutes les exceptions possibles, utilisez <code data-claire-semantic="python">Exception </code>.</p></aside><p id="r-569996" data-claire-element-id="569996">Le mot-clé <code data-claire-semantic="python">else </code> permet d'interpréter du code lorsqu'aucune exception n'a été lancée dans le <code data-claire-semantic="python">try: </code>. Ainsi, on pourrait rajouter une lecture du fichier dans le code précédent :</p><pre id="r-569997" data-claire-element-id="569997"><code data-claire-semantic="python">try:
    fichier = open(&quot;foo.txt&quot;, &quot;r&quot;)
    print int(&quot;22&quot;)
except IOError:
    print &quot;Erreur lors de l'ouverture du fichier !&quot;
except ValueError:
    print &quot;Erreur lors de la conversion !&quot;
else:
    print fichier.read()</code></pre><p id="r-569998" data-claire-element-id="569998">Ainsi, si le fichier s'est ouvert sans problème, et le reste du code (ici symbolisé par le <code data-claire-semantic="python">int(&quot;22&quot;) </code>) aussi, le fichier sera lu.</p><aside id="r-570001" data-claire-element-id="570001" data-claire-semantic="information"><p id="r-569999" data-claire-element-id="569999"><code data-claire-semantic="python">else </code> est néanmoins peu utilisé, car il est bien plus pratique de mettre le code dans le <code data-claire-semantic="python">try </code>, comme ceci :</p><pre id="r-570000" data-claire-element-id="570000"><code data-claire-semantic="python">try:
    fichier = open(&quot;foo.txt&quot;, &quot;r&quot;)
    print int(&quot;22&quot;)
    print fichier.read()
except IOError:
    print &quot;Erreur lors de l'ouerture du fichier !&quot;
except ValueError:
    print 'Erreur lors de la conversion !&quot;</code></pre></aside><p id="r-570002" data-claire-element-id="570002">Enfin, le mot-clé <code data-claire-semantic="python">finally </code> permet d'exécuter du code après l'ensemble <code data-claire-semantic="python">try: except: </code>, quoi qu'il arrive (qu'une exception ait été lancée ou non, qu'un <code data-claire-semantic="python">return </code> ou un <code data-claire-semantic="python">break </code> soit rencontré, le bloc <code data-claire-semantic="python">finally: </code> sera interprété).</p>
<aside class="aside-menu">
<ul class="content-menu subchapter" role="navigation">
<li class="tuto">
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9">Les exceptions</a>
</li>
<ul class="subchapter-parts">
<li class="active">
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/les-mots-cles-try-except-else-et-finally">
Les mots-clés try, except, else et finally
</a>
</li>
<li>
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
Liste des exceptions built-in
</a>
</li>
<li>
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/vos-propres-exceptions">
Vos propres exceptions
</a>
</li>
</ul>
</ul>
</aside>
</div>
<div id="content-bottom-menu"></div>
<hr/>
<div class="paginate-tuto">
<a class="after" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
<span class="next">Liste des exceptions built-in</span>
<span class="arrow"></span>
</a>
</div>
<hr class="bottom"/>
<div class="clear"></div> <div class="adBan">
<script type='text/javascript'>
    if (window.innerWidth >= 728)
    {
        document.write('<div id="div-gpt-ad-1350977194635-8" class="megaban"></div>');
        googletag.cmd.push(function() {
            googletag.display('div-gpt-ad-1350977194635-8');
        });
    }
            else
        {
            document.write('<div id="div-gpt-ad-1350977284180-8" class="miniban"></div>');
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1350977284180-8');
            });
        }
    </script>
</div>
<div class="clear"></div><a name="Listedesexceptionsbuilt-in"></a><h2>Liste des exceptions built-in</h2><div class="paginate-tuto">
<a class="before" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/les-mots-cles-try-except-else-et-finally">
<span class="arrow"></span>
<span class="next">Les mots-clés try, except, else et finally</span>
</a>
<a class="after" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/vos-propres-exceptions">
<span class="next">Vos propres exceptions</span>
<span class="arrow"></span>
</a>
</div>
<hr class="top"/>
<div class="clear"></div> <div id="content" role="article">
<p id="r-570004" data-claire-element-id="570004">Cette partie propose une liste des exceptions built-in en Python, accompagnées pour la plupart d'un exemple.<br/> Certaines exceptions en contiennent d'autres : par exemple, <code data-claire-semantic="python">Exception </code> regroupe toutes les exceptions, exceptés <code data-claire-semantic="python">KeyboardInterrupt </code>, <code data-claire-semantic="python">SystemExit </code>, et bien sûr, <code data-claire-semantic="python">BaseException </code>, qui regroupe l'ensemble des exceptions. La hiérarchie est la suivante :</p><ul id="r-570113" data-claire-element-id="570113"><li id="r-570112" data-claire-element-id="570112"><p id="r-570005" data-claire-element-id="570005">BaseException</p><ul id="r-570111" data-claire-element-id="570111"><li id="r-570007" data-claire-element-id="570007"><p id="r-570006" data-claire-element-id="570006">SystemExit</p></li><li id="r-570009" data-claire-element-id="570009"><p id="r-570008" data-claire-element-id="570008">KeyboardInterrupt</p></li><li id="r-570110" data-claire-element-id="570110"><p id="r-570010" data-claire-element-id="570010">Exception</p><ul id="r-570109" data-claire-element-id="570109"><li id="r-570012" data-claire-element-id="570012"><p id="r-570011" data-claire-element-id="570011">GeneratorExit</p></li><li id="r-570014" data-claire-element-id="570014"><p id="r-570013" data-claire-element-id="570013">StopIteration</p></li><li id="r-570089" data-claire-element-id="570089"><p id="r-570015" data-claire-element-id="570015">StandardError</p><ul id="r-570088" data-claire-element-id="570088"><li id="r-570024" data-claire-element-id="570024"><p id="r-570016" data-claire-element-id="570016">ArithmeticError</p><ul id="r-570023" data-claire-element-id="570023"><li id="r-570018" data-claire-element-id="570018"><p id="r-570017" data-claire-element-id="570017">FloatingPointError</p></li><li id="r-570020" data-claire-element-id="570020"><p id="r-570019" data-claire-element-id="570019">OverflowError</p></li><li id="r-570022" data-claire-element-id="570022"><p id="r-570021" data-claire-element-id="570021">ZeroDivisionError</p></li></ul></li><li id="r-570026" data-claire-element-id="570026"><p id="r-570025" data-claire-element-id="570025">AssertionError</p></li><li id="r-570028" data-claire-element-id="570028"><p id="r-570027" data-claire-element-id="570027">AttributeError</p></li><li id="r-570087" data-claire-element-id="570087"><p id="r-570029" data-claire-element-id="570029">EnvironmentError</p><ul id="r-570086" data-claire-element-id="570086"><li id="r-570031" data-claire-element-id="570031"><p id="r-570030" data-claire-element-id="570030">IOError</p></li><li id="r-570036" data-claire-element-id="570036"><p id="r-570032" data-claire-element-id="570032">OSError</p><ul id="r-570035" data-claire-element-id="570035"><li id="r-570034" data-claire-element-id="570034"><p id="r-570033" data-claire-element-id="570033">VMSError</p></li></ul></li><li id="r-570038" data-claire-element-id="570038"><p id="r-570037" data-claire-element-id="570037">EOFError</p></li><li id="r-570040" data-claire-element-id="570040"><p id="r-570039" data-claire-element-id="570039">ImportError</p></li><li id="r-570047" data-claire-element-id="570047"><p id="r-570041" data-claire-element-id="570041">LookupError</p><ul id="r-570046" data-claire-element-id="570046"><li id="r-570043" data-claire-element-id="570043"><p id="r-570042" data-claire-element-id="570042">IndexError</p></li><li id="r-570045" data-claire-element-id="570045"><p id="r-570044" data-claire-element-id="570044">KeyError</p></li></ul></li><li id="r-570049" data-claire-element-id="570049"><p id="r-570048" data-claire-element-id="570048">MemoryError</p></li><li id="r-570054" data-claire-element-id="570054"><p id="r-570050" data-claire-element-id="570050">NameError</p><ul id="r-570053" data-claire-element-id="570053"><li id="r-570052" data-claire-element-id="570052"><p id="r-570051" data-claire-element-id="570051">UnboundLocalError</p></li></ul></li><li id="r-570056" data-claire-element-id="570056"><p id="r-570055" data-claire-element-id="570055">ReferenceError</p></li><li id="r-570061" data-claire-element-id="570061"><p id="r-570057" data-claire-element-id="570057">RuntimeError</p><ul id="r-570060" data-claire-element-id="570060"><li id="r-570059" data-claire-element-id="570059"><p id="r-570058" data-claire-element-id="570058">NotImplementedError</p></li></ul></li><li id="r-570069" data-claire-element-id="570069"><p id="r-570062" data-claire-element-id="570062">SyntaxError</p><ul id="r-570068" data-claire-element-id="570068"><li id="r-570067" data-claire-element-id="570067"><p id="r-570063" data-claire-element-id="570063">IndentationError</p><ul id="r-570066" data-claire-element-id="570066"><li id="r-570065" data-claire-element-id="570065"><p id="r-570064" data-claire-element-id="570064">TabError</p></li></ul></li></ul></li><li id="r-570071" data-claire-element-id="570071"><p id="r-570070" data-claire-element-id="570070">SystemError</p></li><li id="r-570073" data-claire-element-id="570073"><p id="r-570072" data-claire-element-id="570072">TypeError</p></li><li id="r-570085" data-claire-element-id="570085"><p id="r-570074" data-claire-element-id="570074">ValueError</p><ul id="r-570084" data-claire-element-id="570084"><li id="r-570083" data-claire-element-id="570083"><p id="r-570075" data-claire-element-id="570075">UnicodeError</p><ul id="r-570082" data-claire-element-id="570082"><li id="r-570077" data-claire-element-id="570077"><p id="r-570076" data-claire-element-id="570076">UnicodeDecodeError</p></li><li id="r-570079" data-claire-element-id="570079"><p id="r-570078" data-claire-element-id="570078">UnicodeEncodeError</p></li><li id="r-570081" data-claire-element-id="570081"><p id="r-570080" data-claire-element-id="570080">UnicodeTranslateError</p></li></ul></li></ul></li></ul></li></ul></li><li id="r-570108" data-claire-element-id="570108"><p id="r-570090" data-claire-element-id="570090">Warning</p><ul id="r-570107" data-claire-element-id="570107"><li id="r-570092" data-claire-element-id="570092"><p id="r-570091" data-claire-element-id="570091">DeprecationWarning</p></li><li id="r-570094" data-claire-element-id="570094"><p id="r-570093" data-claire-element-id="570093">PendingDeprecationWarning</p></li><li id="r-570096" data-claire-element-id="570096"><p id="r-570095" data-claire-element-id="570095">RuntimeWarning</p></li><li id="r-570098" data-claire-element-id="570098"><p id="r-570097" data-claire-element-id="570097">SyntaxWarning</p></li><li id="r-570100" data-claire-element-id="570100"><p id="r-570099" data-claire-element-id="570099">UserWarning</p></li><li id="r-570102" data-claire-element-id="570102"><p id="r-570101" data-claire-element-id="570101">FutureWarning</p></li><li id="r-570104" data-claire-element-id="570104"><p id="r-570103" data-claire-element-id="570103">ImportWarning</p></li><li id="r-570106" data-claire-element-id="570106"><p id="r-570105" data-claire-element-id="570105">UnicodeWarning</p></li></ul></li></ul></li></ul></li></ul><ul id="r-570212" data-claire-element-id="570212"><li id="r-570115" data-claire-element-id="570115"><p id="r-570114" data-claire-element-id="570114"><code data-claire-semantic="python">BaseException </code> regroupe l'ensemble des exceptions built-in. Les exceptions définies par l'utilisateur (comme nous allons apprendre à le faire) ne doivent pas en hériter directement, mais hériter d'<code data-claire-semantic="python">Exception </code>.</p></li><li id="r-570117" data-claire-element-id="570117"><p id="r-570116" data-claire-element-id="570116"><code data-claire-semantic="python">SystemExit </code> est l'exception lancée par <code data-claire-semantic="python">sys.exit() </code>. Si elle n'est pas interceptée par un <code data-claire-semantic="python">except: </code>, le programme s'arrête. Elle n'hérite pas d'<code data-claire-semantic="python">Exception </code> pour que, lorsque le développeur cherche à intercepter toutes les erreurs possibles, il n'empêche pas le programme de quitter.</p></li><li id="r-570119" data-claire-element-id="570119"><p id="r-570118" data-claire-element-id="570118"><code data-claire-semantic="python">KeyboardInterrupt </code> est lancé lorsque l'utilisateur appuie sur les touches d'interruption (généralement Ctrl + C). Tout comme SystemExit, il hérite directement de <code data-claire-semantic="python">BaseException </code>, pour les mêmes raisons.</p></li><li id="r-570122" data-claire-element-id="570122"><p id="r-570120" data-claire-element-id="570120"><code data-claire-semantic="python">Exception </code> regroupe toutes les exceptions qui ne se rapportent pas à la fermeture du programme. Vos propres exceptions doivent en dériver. On l'utilise généralement pour s'assurer que tout a bien fonctionné, et dans le cas contraire, pour intercepter puis afficher l'erreur qui s'est produite :</p><pre id="r-570121" data-claire-element-id="570121"><code data-claire-semantic="python">try:
    # code
except Exception, e:
    print &quot;Erreur : %s&quot;, % e</code></pre></li><li id="r-570124" data-claire-element-id="570124"><p id="r-570123" data-claire-element-id="570123"><code data-claire-semantic="python">GeneratorExit </code> est lancé lorsqu'on utilise la méthode <code data-claire-semantic="python">close() </code> d'un générateur. Pour en savoir plus sur les générateurs, je vous conseille le tutoriel de <a href="http://www.siteduzero.com/membres-294-85.html">Natim</a> sur les <a href="http://www.siteduzero.com/tuto-3-33007-1-pratiques-avancees-et-meconnues-en-python.html"> pratiques avancées et méconnues en Python</a>, qui fournit notamment un exemple d'utilisation de cette exception.</p></li><li id="r-570126" data-claire-element-id="570126"><p id="r-570125" data-claire-element-id="570125"><code data-claire-semantic="python">StopIteration </code> est, lui aussi, lié aux générateurs. Le tutoriel précédemment cité en parle également.</p></li><li id="r-570128" data-claire-element-id="570128"><p id="r-570127" data-claire-element-id="570127"><code data-claire-semantic="python">StandardError </code> regroupe toutes les exceptions, sauf les Warnings, <code data-claire-semantic="python">GeneratorExit </code> et <code data-claire-semantic="python">StopIteration </code> puisqu'il ne s'agit pas d'erreurs à proprement parler.</p></li><li id="r-570130" data-claire-element-id="570130"><p id="r-570129" data-claire-element-id="570129"><code data-claire-semantic="python">ArithmeticError </code> est la classe de base pour les erreurs d'arithmétique.</p></li><li id="r-570132" data-claire-element-id="570132"><p id="r-570131" data-claire-element-id="570131"><code data-claire-semantic="python">FloatingPointError </code> est lancé lorsqu'une erreur est détectée dans une opération à <a href="http://fr.wikipedia.org/wiki/Virgule_flottante">virgule flottante</a>.</p></li><li id="r-570134" data-claire-element-id="570134"><p id="r-570133" data-claire-element-id="570133"><code data-claire-semantic="python">OverflowError </code> est lancé lorsque le résultat d'une opération est trop grand pour être représenté.</p></li><li id="r-570138" data-claire-element-id="570138"><p id="r-570135" data-claire-element-id="570135"><code data-claire-semantic="python">ZeroDivisionError </code> est l'exception lancée lorsque le programme tente de faire une division (ou un modulo) par zéro.</p><pre id="r-570136" data-claire-element-id="570136"><code data-claire-semantic="python">try:
    print 5/0
except ZeroDivisionError, e:
    print e

try:
    print 5%0
except ZeroDivisionError, e:
    print e</code></pre><pre id="r-570137" data-claire-element-id="570137"><code data-claire-semantic="console">integer division or modulo by zero
integer division or modulo by zero</code></pre></li><li id="r-570142" data-claire-element-id="570142"><p id="r-570139" data-claire-element-id="570139"><code data-claire-semantic="python">AssertionError </code> est lancé lorsqu'un <code data-claire-semantic="python">assert </code> n'est pas vrai.</p><pre id="r-570140" data-claire-element-id="570140"><code data-claire-semantic="python">try:
    assert 1 == 0
except AssertionError:
    print &quot;Erreur !&quot;</code></pre><pre id="r-570141" data-claire-element-id="570141"><code data-claire-semantic="console">Erreur !</code></pre></li><li id="r-570146" data-claire-element-id="570146"><p id="r-570143" data-claire-element-id="570143"><code data-claire-semantic="python">AttributeError </code> est lancé lorsqu'une erreur se produit lors d'une référence ou d'un assignement à un attribut.</p><pre id="r-570144" data-claire-element-id="570144"><code data-claire-semantic="python">class Foo:
    pass

foo = Foo()
try:
    print foo.bar
except AttributeError, e:
    print e</code></pre><pre id="r-570145" data-claire-element-id="570145"><code data-claire-semantic="console">Foo instance has no attribute 'bar'</code></pre></li><li id="r-570148" data-claire-element-id="570148"><p id="r-570147" data-claire-element-id="570147"><code data-claire-semantic="python">EnvironmentError </code> est la classe de base des exceptions qui ne proviennent pas de Python (par exemple, un fichier introuvable).</p></li><li id="r-570152" data-claire-element-id="570152"><p id="r-570149" data-claire-element-id="570149"><code data-claire-semantic="python">IOError </code> est une exception lancée lorsqu'une erreur I/O (pour Input/Output) se produit. Trois attributs sont intéressants : <code data-claire-semantic="python">errno </code>, qui indique le numéro de l'erreur ; <code data-claire-semantic="python">filename </code>, qui donne le nom du fichier concerné ; et <code data-claire-semantic="python">strerror </code> qui donne une description de l'erreur.</p><pre id="r-570150" data-claire-element-id="570150"><code data-claire-semantic="python">try:
    fichier = open(&quot;foo.txt&quot;, &quot;r&quot;)
except IOError, e:
    print &quot;Erreur&quot;, e.errno, &quot;:&quot;, e.filename, &quot;n'a pas pu être ouvert (&quot;, e.strerror, &quot;).&quot;</code></pre><pre id="r-570151" data-claire-element-id="570151"><code data-claire-semantic="console">Erreur 2 : foo.txt n'a pas pu être ouvert ( No such file or directory ).</code></pre></li><li id="r-570154" data-claire-element-id="570154"><p id="r-570153" data-claire-element-id="570153"><code data-claire-semantic="python">OSError </code> est l'exception utilisée par le module <code data-claire-semantic="python">os </code>.</p></li><li id="r-570159" data-claire-element-id="570159"><p id="r-570155" data-claire-element-id="570155"><code data-claire-semantic="python">EOFError </code> est lancé lorsque les fonctions <code data-claire-semantic="python">input() </code> et <code data-claire-semantic="python">raw_input() </code> reçoivent le signal EOF (pour End Of File).</p><pre id="r-570156" data-claire-element-id="570156"><code data-claire-semantic="python">try:
    input()
except EOFError:
    print &quot;Erreur !&quot;</code></pre><p id="r-570157" data-claire-element-id="570157">Si vous envoyez le signal EOF pendant l'<code data-claire-semantic="python">input() </code> (généralement, c'est la combinaison de touches Ctrl + D) :</p><pre id="r-570158" data-claire-element-id="570158"><code data-claire-semantic="console">Erreur !</code></pre></li><li id="r-570163" data-claire-element-id="570163"><p id="r-570160" data-claire-element-id="570160"><code data-claire-semantic="python">ImportError </code> est lancé lorsqu'une erreur se produit lors d'un <code data-claire-semantic="python">import </code>.</p><pre id="r-570161" data-claire-element-id="570161"><code data-claire-semantic="python">try:
    import foo
except ImportError, e:
    print e
try:
    from os import bar
except ImportError, e:
    print e</code></pre><pre id="r-570162" data-claire-element-id="570162"><code data-claire-semantic="console">No module named foo
cannot import name bar</code></pre></li><li id="r-570165" data-claire-element-id="570165"><p id="r-570164" data-claire-element-id="570164"><code data-claire-semantic="python">LookupError </code> est la classe de base pour les exceptions <code data-claire-semantic="python">IndexError </code> et <code data-claire-semantic="python">KeyError </code>.</p></li><li id="r-570169" data-claire-element-id="570169"><p id="r-570166" data-claire-element-id="570166"><code data-claire-semantic="python">IndexError </code> est lancé quand l'index d'un tableau n'est pas valide (mais reste un nombre ; autrement, c'est <code data-claire-semantic="python">TypeError </code> qui est utilisé).</p><pre id="r-570167" data-claire-element-id="570167"><code data-claire-semantic="python">foo = [0,1,2]
try:
    print foo[3]
except IndexError, e:
    print e</code></pre><pre id="r-570168" data-claire-element-id="570168"><code data-claire-semantic="console">list index out of range</code></pre></li><li id="r-570171" data-claire-element-id="570171"><p id="r-570170" data-claire-element-id="570170"><code data-claire-semantic="python">KeyError </code> est l'équivalent d'<code data-claire-semantic="python">IndexError </code> pour les dictionnaires.</p></li><li id="r-570173" data-claire-element-id="570173"><p id="r-570172" data-claire-element-id="570172"><code data-claire-semantic="python">MemoryError </code> est lancé lorsqu'un programme prend trop de mémoire.</p></li><li id="r-570177" data-claire-element-id="570177"><p id="r-570174" data-claire-element-id="570174"><code data-claire-semantic="python">NameError </code> est lancé quand un nom local ou global est introuvable.</p><pre id="r-570175" data-claire-element-id="570175"><code data-claire-semantic="python">try:
    print foo
except NameError, e:
    print e</code></pre><pre id="r-570176" data-claire-element-id="570176"><code data-claire-semantic="console">name 'foo' is not defined</code></pre></li><li id="r-570181" data-claire-element-id="570181"><p id="r-570178" data-claire-element-id="570178"><code data-claire-semantic="python">UnboundLocalError </code> est lancé lorsqu'une référence à une variable à laquelle aucune valeur n'a été donnée est faite dans une fonction ou une méthode.</p><pre id="r-570179" data-claire-element-id="570179"><code data-claire-semantic="python">def foo():
    bar += 1

try:
    foo()
except UnboundLocalError, e:
    print e</code></pre><pre id="r-570180" data-claire-element-id="570180"><code data-claire-semantic="console">local variable 'bar' referenced before assignment</code></pre></li><li id="r-570183" data-claire-element-id="570183"><p id="r-570182" data-claire-element-id="570182"><code data-claire-semantic="python">ReferenceError </code> est une exception spécifique au module <code data-claire-semantic="python"><a href="http://docs.python.org/lib/module-weakref.html">weakref </a></code>.</p></li><li id="r-570185" data-claire-element-id="570185"><p id="r-570184" data-claire-element-id="570184"><code data-claire-semantic="python">RuntimeError </code> est utilisé pour toutes les erreurs ne rentrant pas dans les autres catégories.</p></li><li id="r-570187" data-claire-element-id="570187"><p id="r-570186" data-claire-element-id="570186"><code data-claire-semantic="python">NotImplementedError </code> est utilisé dans les fonctions définies par l'utilisateur, pour informer (comme son nom l'indique) que ce qui est demandé n'est pas implémenté.</p></li><li id="r-570189" data-claire-element-id="570189"><p id="r-570188" data-claire-element-id="570188"><code data-claire-semantic="python">SyntaxError </code> est lancé lorsque l'interpréteur trouve une erreur de syntaxe. Cela peut arriver lorsque vous importez du code, que vous utilisez <code data-claire-semantic="python">exec </code>, <code data-claire-semantic="python">eval() </code>, <code data-claire-semantic="python">input() </code> ou que le script ou la ligne que vous venez d'entrer dans l'interpréteur sont lus.</p></li><li id="r-570191" data-claire-element-id="570191"><p id="r-570190" data-claire-element-id="570190"><code data-claire-semantic="python">IndentationError </code> est un dérivé de <code data-claire-semantic="python">SyntaxError </code> et, comme son nom l'indique, apparaît lorsqu'une erreur d'indentation est détectée.</p></li><li id="r-570193" data-claire-element-id="570193"><p id="r-570192" data-claire-element-id="570192"><code data-claire-semantic="python">SystemError </code> indique une erreur interne de l'interpréteur.</p></li><li id="r-570197" data-claire-element-id="570197"><p id="r-570194" data-claire-element-id="570194"><code data-claire-semantic="python">TypeError </code> est lancé quand une opération ou une fonction est faite sur un objet de type inapproprié.</p><pre id="r-570195" data-claire-element-id="570195"><code data-claire-semantic="python">try:
    print int([0,1])
except TypeError, e:
    print e</code></pre><pre id="r-570196" data-claire-element-id="570196"><code data-claire-semantic="console">int() argument must be a string or a number</code></pre></li><li id="r-570199" data-claire-element-id="570199"><p id="r-570198" data-claire-element-id="570198"><code data-claire-semantic="python">ValueError </code> indique qu'une fonction ou une opération a reçu un argument du bon type, mais avec une valeur incorrecte. Par exemple, <code data-claire-semantic="python">int(&quot;abc&quot;) </code> produit une telle erreur : &quot;abc&quot; est bien une chaîne, mais n'est pas convertible en un nombre.</p></li><li id="r-570201" data-claire-element-id="570201"><p id="r-570200" data-claire-element-id="570200"><code data-claire-semantic="python">UnicodeError </code> est lancé quand une erreur lors d'un encodage ou décodage Unicode se produit.</p></li><li id="r-570203" data-claire-element-id="570203"><p id="r-570202" data-claire-element-id="570202"><code data-claire-semantic="python">UnicodeDecodeError </code> indique que l'erreur s'est produite lors du décodage.</p></li><li id="r-570205" data-claire-element-id="570205"><p id="r-570204" data-claire-element-id="570204"><code data-claire-semantic="python">UnicodeEncodeError </code> indique que c'était durant l'encodage.</p></li><li id="r-570207" data-claire-element-id="570207"><p id="r-570206" data-claire-element-id="570206">Enfin, <code data-claire-semantic="python">UnicodeTranslateError </code> indique que c'était durant une translation.</p></li><li id="r-570209" data-claire-element-id="570209"><p id="r-570208" data-claire-element-id="570208"><code data-claire-semantic="python">Warning </code> est la classe de base pour les Warnings.</p></li><li id="r-570211" data-claire-element-id="570211"><p id="r-570210" data-claire-element-id="570210"><code data-claire-semantic="python">UserWarning </code> est la classe de base pour les warnings définis par l'utilisateur.</p></li></ul><p id="r-570213" data-claire-element-id="570213">Les autres Warnings portent des noms tout à fait explicites, si bien qu'il est inutile de radoter autour.</p>
<aside class="aside-menu">
<ul class="content-menu subchapter" role="navigation">
<li class="tuto">
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9">Les exceptions</a>
</li>
<ul class="subchapter-parts">
<li>
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/les-mots-cles-try-except-else-et-finally">
Les mots-clés try, except, else et finally
</a>
</li>
<li class="active">
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
Liste des exceptions built-in
</a>
</li>
<li>
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/vos-propres-exceptions">
Vos propres exceptions
</a>
</li>
</ul>
</ul>
</aside>
</div>
<div id="content-bottom-menu"></div>
<hr/>
<div class="paginate-tuto">
<a class="before" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/les-mots-cles-try-except-else-et-finally">
<span class="arrow"></span>
<span class="next">Les mots-clés try, except, else et finally</span>
</a>
<a class="after" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/vos-propres-exceptions">
<span class="next">Vos propres exceptions</span>
<span class="arrow"></span>
</a>
</div>
<hr class="bottom"/>
<div class="clear"></div> <div class="adBan">
<script type='text/javascript'>
    if (window.innerWidth >= 728)
    {
        document.write('<div id="div-gpt-ad-1350977194635-8" class="megaban"></div>');
        googletag.cmd.push(function() {
            googletag.display('div-gpt-ad-1350977194635-8');
        });
    }
            else
        {
            document.write('<div id="div-gpt-ad-1350977284180-8" class="miniban"></div>');
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1350977284180-8');
            });
        }
    </script>
</div>
<div class="clear"></div><a name="Vospropresexceptions"></a><h2>Vos propres exceptions</h2><div class="paginate-tuto">
<a class="before" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
<span class="arrow"></span>
<span class="next">Liste des exceptions built-in</span>
</a>
</div>
<hr class="top"/>
<div class="clear"></div> <div id="content" role="article">
<p id="r-570215" data-claire-element-id="570215">Pour des raisons pratiques, vous serez peut-être amené(e) un jour à faire vos propres exceptions.<br/> Nous allons comprendre comment le faire en analysant ce code :</p><pre id="r-570216" data-claire-element-id="570216"><code data-claire-semantic="python">class MonException(Exception):
    def __init__(self,raison):
        self.raison = raison
    
    def __str__(self):
        return self.raison

def multiplier_par_5(n):
    if n &gt; 20:
        raise MonException(&quot;Le nombre est trop grand !&quot;)
    else:
        return n * 5</code></pre><p id="r-570217" data-claire-element-id="570217">Nous créons ici une classe nommée <em>MonException</em>, avec deux méthodes. <code data-claire-semantic="python">__init__ </code> prend comme argument <em>raison</em>. La fonction <code data-claire-semantic="python">__str__ </code> est celle qui est appelée lorsqu'on tente d'afficher l'instance de l'exception que j'ai jusqu'ici appelée <em>e</em>. Ici, elle renvoie <em>raison</em>.<br/> Il y a ensuite une fonction <code data-claire-semantic="python">multiplier_par_5() </code>, qui multiplie l'argument <em>n</em> par 5 à condition que celui-ci ne soit pas plus grand que 20. Dans le cas contraire, on utilise le mot-clé <code data-claire-semantic="python">raise </code> pour lancer l'exception. C'est aussi simple que cela.<br/> Finalement, cette fonction utilisée pourrait donner ceci :</p><pre id="r-570218" data-claire-element-id="570218"><code data-claire-semantic="python">try:
    print multiplier_par_5(2)
    print multiplier_par_5(21)
except MonException, e:
    print e</code></pre><pre id="r-570219" data-claire-element-id="570219"><code data-claire-semantic="console">10
Le nombre est trop grand !</code></pre><p id="r-570220" data-claire-element-id="570220">Maintenant, vous pouvez ajouter des attributs (comme par exemple la taille du nombre envoyé, pour que <code data-claire-semantic="python">__str__ </code> puisse afficher « Le nombre 21 est trop grand ! » par exemple. De plus, l'utilisateur pourrait s'en servir pour afficher l'erreur soi-même, par exemple en faisant <code data-claire-semantic="python">print e.n, &quot;est plus grand que 20 ; erreur !&quot; </code>.</p><p id="r-570221" data-claire-element-id="570221">Vous voilà désormais capable de gérer tout type d'erreur en Python.<br/> En effet, lorsque vous faites <code data-claire-semantic="python">int() </code>, avec une chaîne qui n'est pas transformable en un nombre, vous obtenez une <code data-claire-semantic="python">ValueError </code>. Vous n'avez qu'à faire une boucle, et ne pas la terminer tant que vous obtiendrez une <code data-claire-semantic="python">ValueError </code>. Voici mon code :</p><pre id="r-570222" data-claire-element-id="570222"><code data-claire-semantic="python">while 1:
    try:
        a = int(raw_input(&quot;Entrez un nombre : &quot;))
        break
    except ValueError:
        print &quot;Ce n'est pas un nombre !&quot;
print a*3</code></pre><div id="r-570224" data-claire-element-id="570224"><p id="r-570223" data-claire-element-id="570223"><em>Merci à #python pour les conseils qui m'ont été donnés, et à Klouguinette pour sa zCorrection incomparable. :')</em></p></div>
<aside class="aside-menu">
<ul class="content-menu subchapter" role="navigation">
<li class="tuto">
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9">Les exceptions</a>
</li>
<ul class="subchapter-parts">
<li>
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/les-mots-cles-try-except-else-et-finally">
Les mots-clés try, except, else et finally
</a>
</li>
<li>
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
Liste des exceptions built-in
</a>
</li>
<li class="active">
<a href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/vos-propres-exceptions">
Vos propres exceptions
</a>
</li>
</ul>
</ul>
</aside>
</div>
<div id="content-bottom-menu"></div>
<hr/>
<div class="paginate-tuto">
<a class="before" href="http://62.4.17.167/informatique/tutoriels/les-exceptions-9/liste-des-exceptions-built-in">
<span class="arrow"></span>
<span class="next">Liste des exceptions built-in</span>
</a>
</div>
<hr class="bottom"/>
<div class="clear"></div> <div class="adBan">
<script type='text/javascript'>
    if (window.innerWidth >= 728)
    {
        document.write('<div id="div-gpt-ad-1350977194635-8" class="megaban"></div>');
        googletag.cmd.push(function() {
            googletag.display('div-gpt-ad-1350977194635-8');
        });
    }
            else
        {
            document.write('<div id="div-gpt-ad-1350977284180-8" class="miniban"></div>');
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1350977284180-8');
            });
        }
    </script>
</div>
<div class="clear"></div>
</body>
<!-- Mirrored from 62.4.17.167/sdz/sdz/les-exceptions-9.html by HTTrack Website Copier/3.x [XR&CO'2013], Sun, 27 Oct 2013 05:39:43 GMT -->

<!-- Mirrored from sdz.tdct.org/sdz/les-exceptions-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Nov 2015 05:00:15 GMT -->
</html>